language: bash
sudo: required
services:
  - docker
install:
  - docker build -t container:latest .
  - docker ps -a
script:
  - docker run -it --rm -v $PWD:/home/user/work -e MY_UID=$UID container ./test
